# Generated by Django 5.2.1 on 2025-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_title", models.CharField(max_length=255)),
                ("problem_description", models.CharField(max_length=255)),
                ("problem_summary", models.CharField(max_length=255)),
                ("pseudo_code", models.CharField(max_length=255)),
                ("source_code", models.CharField(max_length=255)),
                ("submit_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
