# Generated by Django 5.2.1 on 2025-06-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problems",
            name="problem_description",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="problems",
            name="problem_summary",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="problems",
            name="problem_title",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="problems",
            name="pseudo_code",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="problems",
            name="source_code",
            field=models.CharField(max_length=10000),
        ),
    ]
