# Generated by Django 5.2.1 on 2025-06-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemlog", "0002_alter_problems_problem_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problems",
            name="solved",
            field=models.CharField(default="unsolved", max_length=50),
            preserve_default=False,
        ),
    ]
