# Generated by Django 5.2.1 on 2025-06-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemlog", "0003_problems_solved"),
    ]

    operations = [
        migrations.AddField(
            model_name="problems",
            name="username",
            field=models.CharField(default=" ", max_length=255),
            preserve_default=False,
        ),
    ]
