# Generated by Django 5.2.1 on 2025-07-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemlog", "0005_problemversions"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemversions",
            name="version_number",
            field=models.IntegerField(default=0),
        ),
    ]
