# Generated by Django 5.2.7 on 2025-11-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problemlog", "0007_alter_problemversions_version_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problemversions",
            old_name="problem_id",
            new_name="problem",
        ),
    ]
