# Generated by Django 5.2.1 on 2025-06-10 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemlog", "0004_problems_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemVersions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("problem_title", models.CharField(max_length=10000)),
                ("problem_description", models.CharField(max_length=10000)),
                ("problem_summary", models.CharField(max_length=10000)),
                ("pseudo_code", models.CharField(max_length=10000)),
                ("source_code", models.CharField(max_length=10000)),
                ("solved", models.CharField(max_length=50)),
                ("submit_time", models.DateTimeField(auto_now_add=True)),
                (
                    "problem_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problemlog.problems",
                    ),
                ),
            ],
        ),
    ]
