# Generated by Django 5.2.1 on 2025-07-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemlog", "0006_problemversions_version_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemversions",
            name="version_number",
            field=models.IntegerField(default=1),
        ),
    ]
